Hotfix: compilation issue, bump Android SDK v. 31
symbol/mobile-wallet pull request #335
Opened 2023-08-31 13:23 UTC by OlegMakarenko

**Problem**
- Comilation issue descibed here: https://github.com/facebook/react-native/issues/35210
- Warning from Android Play Store: 

> App not available to new users on Android versions higher than your target API level
> App must target Android 12 (API level 31) or higher

**Solution**
- Updated configuration in `build.gradle`.
- Bump SDK version to 31.
- Declare the android:exported in the activities that use intent filters.
- Remove unused dependency that caused upgrade issue (react-native-background-fetch).

2023-08-31 15:29 UTC, Wayonb requested changes

2023-08-31 15:29 UTC, Wayonb commented on README.md
> +- Node version should be from **12.1.0** to **17.9.1**.
Node 12 is really old.  I would increase the node version from 12.1.0 to 16.x if possible.
Even though node 16 will not be supported in a couple of weeks.
``from **16.x** to **17.9.1**.``

2023-08-31 15:29 UTC, Wayonb commented on android/build.gradle
> +            ndkVersion = "24.0.8215888"
Is there a reason not to use this ``ndkVersion``  as the minimum for all platforms?

2023-09-01 10:41 UTC, OlegMakarenko commented
@Wayonb thanks, fixed.

2023-09-01 12:13 UTC, Wayonb approved these changes
👍🏾

2023-09-01 14:09 UTC, AnthonyLaw approved these changes

2023-09-04 10:46 UTC, merged